### PR TITLE
added missing API declaration

### PR DESCRIPTION
**Pull request by odise**

### CODE REVIEW

**Comment by atc0005** [comment]
@odise If you're comfortable doing so, could you squash the two commits/rebase and update your branch?

**Comment by odise** [comment]
@atc0005 you can squash the PR directly here on Github when you merge it. I rebased it already.

**Comment by atc0005** [comment]
> @atc0005 you can squash the PR directly here on Github when you merge it.

I've tried GitHub's support for `Allow squash merging` and `Allow rebase merging` before, but those didn't function as expected and instead skipped the merge commit step.

> I rebased it already.

I see that you merged master into your branch, but I meant squash the commits so that your branch only has one. Instead of running `git merge master` earlier after making your commit, you would have run `git rebase master` instead.

**EDIT**

Nevermind, I see now. You reused your earlier branch instead of creating a new one for this PR. My earlier remarks were based on an assumption that we were looking at a new branch.

**Review by atc0005 — APPROVED** [review]
Thanks for the API interface update.

**Pull request merged**
