### PR TITLE
Validate custom office webhook URL

### PR DESCRIPTION
**Pull request by denysvitali**
As previously opened here: https://github.com/dasrick/go-teams-notify/pull/25

### CODE REVIEW

**Comment by atc0005** [comment]
@denysvitali 

Thanks for your interest in this project.

The functionality contained in your PR has been implemented previously in this project, albeit in different forms.

See the current README examples, or PRs #86 and #93 for details.

**Comment by atc0005** [comment]
@denysvitali Do you have any interest in rebasing this PR and providing an alternate set of changes? If not, I can go ahead and close it for now.

**Comment by denysvitali** [comment]
I guess your solution should already solve the problem, so we can close this PR ;)

**Comment by atc0005** [comment]
@denysvitali Thanks for the feedback. Closing.

**Pull request closed without merging**
