### PR TITLE
Added structs to supports potential actions

### PR DESCRIPTION
**Pull request by nmaupu**
Added support for PotentialActions.
See https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference#actions

### CODE REVIEW

**Comment by atc0005** [comment]
Thanks for submitting this.

It will take me some time to step through the changes and offer detailed feedback, but I wanted to go ahead and throw out some unordered items as they come to mind:

- `potentialAction` property can be specified for the card itself and per section
  - I saw where this is handled for the card itself, but not per section (admittedly I've not finished going over the changes, so I may have missed it)
- https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference#openuri-action
  - it looks like there are only 4 valid values here
  - validate provided value(s) and reject any that do not match known valid values?
- I vaguely recall that there is a fifth type of action, but it is deprecated and not covered on https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference#actions
  - likely not worth implementing if it's going to be dropped in the future

**Comment by atc0005** [comment]
@nmaupu I meant to follow-up before now, apologies for the silence here.

Do you happen to have any test/prototype client code which uses the functionality added by this PR? I'm asking before I make plans to try and work in changes to a small project of my own in order to better test the proposed changes.

**Comment by nmaupu** [comment]
> @nmaupu I meant to follow-up before now, apologies for the silence here.
No prob!

> Do you happen to have any test/prototype client code which uses the functionality added by this PR? I'm asking before I make plans to try and work in changes to a small project of my own in order to better test the proposed changes.

No I don't ATM :/

**Comment by atc0005** [comment]
> I'm coming at this with fresh eyes and haven't gone back over the documentation yet; what is the `name` parameter used for?

I posted this question in-line here:
https://github.com/nmaupu/go-teams-notify/commit/b9e05e82de91ae261ef17269d4bf573bc902c3e6#diff-6e76fa32b560c5449670f8c369fbd67f095af1b2b108e65da37dab3d55a7dddaR554

I'm used to GitHub displaying the applicable portion of the diff alongside comments within the PR "thread". Not sure why it didn't do so this time.

**Comment by atc0005** [comment]
@nmaupu 

Thanks for your patience on this.

I've gotten far enough with a set of changes for a CLI client that I'm getting a good feel for the features this PR adds. Overall, this appears to be a great addition to the library. 

Are you interested in making further changes, or would you like to smooth off any rough edges (e.g., add doc comments in a few places) and consider this PR done? If you'd like to make further changes, I've got some suggestions, but I can hold those for a follow-up PR if you want.

**Comment by atc0005** [comment]
@nmaupu I initially tried to use GitHub to rebase the latest changes from `master`, but they were merged in as new commits instead of fast-forwarding the branch. I ended up dropping that attempt, then rebased and force-pushed.

The result is that the branch is up to date with `master` and the intermediate commits that GitHub created have been dropped. This wasn't as clean as I had hoped, but your branch is rebased and represents where it would be if you had only just opened the PR based on current `master`.

**Review by atc0005 — APPROVED** [review]
Going to approve the PR as-is, then submit further changes (e.g., linting fixes) as part a later PR. See https://github.com/atc0005/go-teams-notify/issues/102#issuecomment-872895417 and https://github.com/atc0005/go-teams-notify/issues/102#issuecomment-872900667 for specifics.

Thanks again for this work, it's a great addition to the library.

**Pull request merged**
